name: court_care
description: Gestion maintenance et événements d’un club de tennis
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter



  # State management
  flutter_riverpod: ^2.5.1

  # Database
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
